### PR TITLE
Fix saving cache taking too long

### LINKED ISSUE #91: Document why setup-pixi is so slow when uploading cache

### PR DESCRIPTION
**Pull request by 0xbe7a**
Fixes #91

When setting up a new Pixi environment for the first time, the `setup-pixi` action currently hangs for up to several minutes, appearing to do nothing. An example can be seen here: https://github.com/Quantco/multiregex/actions/runs/9207365813/job/25327248270.

This issue seems to be caused by an unresolved problem in `actions/toolkit`, which prevents actions from terminating in a timely manner after uploading a new cached artifact, as discussed here: https://github.com/actions/toolkit/issues/1578. A workaround is to force the process to terminate by adding `process.exit(0)` at the end of the execution.

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -129,16 +129,18 @@ const run = async () => {
...
-    core.setFailed(error.message)
-    exit(1)
-  } else if (typeof error === 'string') {
-    core.setFailed(error)
-    exit(1)
-  }
-  throw error
-})
+  })
+  .then(exit(0)) // workaround for https://github.com/actions/toolkit/issues/1578
```
Comment (pavelzw) [inline src/main.ts:146]:
```suggestion
  .then(() => exit(0)) // workaround for https://github.com/actions/toolkit/issues/1578
```

**Review by pavelzw — APPROVED** [review]
Looks good 🥳 
image
